name: Android CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Development build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Setup google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES }}' > ./app/google-services.json

      - name: Setup wathc app google-services.json
        run: echo '${{ secrets.WATCH_GOOGLE_SERVICES }}' > ./app-watch/google-services.json

      - name: Build with Gradle
        run: ./gradlew build
